on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release workflow

jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          draft: true
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile --check-files
      - name: Build tarballs
        working-directory: ${{ github.workspace }}/packages/eas-cli
        run: yarn oclif-dev pack --targets linux-x64,linux-arm
      - name: Upload linux-x64 tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: packages/eas-cli/dist/eas-linux-x64.tar.gz
          asset_name: eas-linux-x64.tar.gz
          asset_content_type: application/gzip
      - name: Upload linux-arm tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: packages/eas-cli/dist/eas-linux-arm.tar.gz
          asset_name: eas-linux-arm.tar.gz
          asset_content_type: application/gzip
  build-mac:
    name: Build for macOS
    # Use macOS to get the platform specific dependencies like traveling-fastlane-darwin
    runs-on: macos-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile --check-files
      - name: Build tarballs
        working-directory: ${{ github.workspace }}/packages/eas-cli
        run: yarn oclif-dev pack --targets darwin-x64
      - name: Upload darwin-x64 tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: packages/eas-cli/dist/eas-darwin-x64.tar.gz
          asset_name: eas-darwin-x64.tar.gz
          asset_content_type: application/gzip
